DROP TABLE IF EXISTS project_users;
DROP TABLE IF EXISTS team_users;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS audits;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;